<?php

?>
<aside class="right-side">
	
 	<section class="content-header">
        <h1>
            Login Page
            <small></small>
        </h1>
        
    </section>

    <!-- Main content -->
    <section class="content">
        <form action="login" method="post">
            <div class="container">
                <label for="uname"><b>Username 1</b></label>
                    <input type="text" placeholder="Enter Username" name="username" required>
                    <br>
                <label for="psw"><b>Password 2</b></label>

                <input type="password" placeholder="Enter Password" name="password" required>
                <br>
                <button type="submit">Login</button>
                <label>
                    <input type="checkbox" checked="checked" name="remember"> Remember me
                </label>
            </div>

            <div class="container" style="background-color:#f1f1f1">
                <button type="button" class="cancelbtn">Cancel</button>
                <span class="psw">Forgot <a href="#">password?</a></span>
            </div>
        </form>


		<?php
            if($user = $this->identity())
            {
                //$this->redirect()->toRoute('application', array('controller' => 'index', 'action' => 'index')); 
                //echo "Logged in as ".$this->escapeHtml($user->user_name);
            }else{
                if(!empty($result)){
                    print_r($result);
                }
            }
		?>
    </section><!-- /.content -->
</aside><!-- /.right-side -->