<?php
$title = "Profile";
$this->headTitle($title);

?>
<aside class="right-side">
	
 	<section class="content-header">
        <h1>
            Profile
            <small>it all starts here</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Blank page</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
    	<?php 
    	
    	foreach ($resultset as $key => $value) {
    		echo $value->first_name." ".$value->middle_name." ".$value->last_name;
            echo "<br>";
            echo $value->email_id;
    	}


        

    	?>

    </section><!-- /.content -->

</aside><!-- /.right-side -->